
alter session set container=ORBUPG;

ALTER TABLESPACE XX_JUNK ADD DATAFILE '+DATA_DG_ORBUPG' size 100m AUTOEXTEND on NEXT 100M MAXSIZE 32000m;
ALTER TABLESPACE XX_JUNK ADD DATAFILE '+DATA_DG_ORBUPG' size 100m AUTOEXTEND on NEXT 100M MAXSIZE 32000m;
ALTER TABLESPACE XX_JUNK ADD DATAFILE '+DATA_DG_ORBUPG' size 100m AUTOEXTEND on NEXT 100M MAXSIZE 32000m;
ALTER TABLESPACE XX_JUNK ADD DATAFILE '+DATA_DG_ORBUPG' size 100m AUTOEXTEND on NEXT 100M MAXSIZE 32000m;
