
alter session set container=ORBUPG;

!echo "Fixing TEMP tablespace"
CREATE TEMPORARY TABLESPACE TEMP_TEMP TEMPFILE '+TEMP_DG_ORBUPG' SIZE 100m;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP_TEMP;
DROP TABLESPACE XX_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TEMP INCLUDING CONTENTS AND DATAFILES;
CREATE TEMPORARY TABLESPACE XX_TEMP TEMPFILE '+TEMP_DG_ORBUPG' SIZE 336M AUTOEXTEND ON maxsize 30g;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE XX_TEMP;
DROP TABLESPACE TEMP_TEMP INCLUDING CONTENTS AND DATAFILES;

!echo "Fixing UNDO tablespace"
CREATE UNDO TABLESPACE APPS_UNDOTS10 DATAFILE '+DATA_DG_ORBUPG' SIZE 336M AUTOEXTEND ON NEXT 336M maxsize 31920M;
CREATE UNDO TABLESPACE APPS_UNDOTS11 DATAFILE '+DATA_DG_ORBUPG' SIZE 336M AUTOEXTEND ON NEXT 336M maxsize 31920M; 
CREATE UNDO TABLESPACE APPS_UNDOTS12 DATAFILE '+DATA_DG_ORBUPG' SIZE 336M AUTOEXTEND ON NEXT 336M maxsize 31920M; 
CREATE UNDO TABLESPACE APPS_UNDOTS13 DATAFILE '+DATA_DG_ORBUPG' SIZE 336M AUTOEXTEND ON NEXT 336M maxsize 31920M; 
alter system set undo_tablespace= 'APPS_UNDOTS10' scope=both sid= 'ORBUPGCD1';
alter system set undo_tablespace= 'APPS_UNDOTS11' scope=both sid= 'ORBUPGCD2';
alter system set undo_tablespace= 'APPS_UNDOTS12' scope=both sid= 'ORBUPGCD3';
drop tablespace APPS_UNDOTS1 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS2 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS3 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS4 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS5 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS6 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS7 INCLUDING CONTENTS AND DATAFILES;

CREATE UNDO TABLESPACE APPS_UNDOTS1 DATAFILE 
'+DATA_DG_ORBUPG' SIZE 336M REUSE AUTOEXTEND ON NEXT 336M maxsize 31920M,
'+DATA_DG_ORBUPG' SIZE 336M REUSE AUTOEXTEND ON NEXT 336M maxsize 31920M;

CREATE UNDO TABLESPACE APPS_UNDOTS2 DATAFILE 
'+DATA_DG_ORBUPG' SIZE 336M REUSE AUTOEXTEND ON NEXT 336M maxsize 31920M,
'+DATA_DG_ORBUPG' SIZE 336M REUSE AUTOEXTEND ON NEXT 336M maxsize 31920M;

CREATE UNDO TABLESPACE APPS_UNDOTS3 DATAFILE 
'+DATA_DG_ORBUPG' SIZE 336M REUSE AUTOEXTEND ON NEXT 336M maxsize 31920M,
'+DATA_DG_ORBUPG' SIZE 336M REUSE AUTOEXTEND ON NEXT 336M maxsize 31920M;

alter system set undo_tablespace='APPS_UNDOTS1' scope=both sid='ORBUPGCD1';
alter system set undo_tablespace='APPS_UNDOTS2' scope=both sid='ORBUPGCD2';
alter system set undo_tablespace='APPS_UNDOTS3' scope=both sid='ORBUPGCD3';

drop tablespace APPS_UNDOTS10 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS11 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS12 INCLUDING CONTENTS AND DATAFILES;
drop tablespace APPS_UNDOTS13 INCLUDING CONTENTS AND DATAFILES;

--shut down database
--start the database
